apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: sre-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-app
  template:
    metadata:
      labels:
        app: sre-app
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: DATABASE_URL
          value: "{{ .Values.env.DATABASE_URL }}"
        - name: PHX_HOST
          value: "{{ .Values.env.PHX_HOST }}"
        - name: SECRET_KEY_BASE
          value: "{{ .Values.env.SECRET_KEY_BASE }}"
        - name: POOL_SIZE
          value: "{{ .Values.env.POOL_SIZE }}"
        ports:
        - containerPort: 4000 
          name: http
        livenessProbe:
          {{ toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{ toYaml .Values.readinessProbe | nindent 10 }}
      {{- if .Values.resources }}
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
      {{- end }}