apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrations
  labels:
    app: sre-app
spec:
  template:
    spec:
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["migrate"] 
          env:
            - name: DATABASE_URL
              value: "{{ .Values.env.DATABASE_URL }}"
            - name: SECRET_KEY_BASE
              value: "{{ .Values.env.SECRET_KEY_BASE }}"
      restartPolicy: Never
