apiVersion: v1
kind: Service
metadata:
  name: sre-app-sre-technical-challenge
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4000
  selector:
    app: sre-app
